######################################################################
# Automatically generated by qmake (3.0) Wed Jan 4 13:30:22 2017
######################################################################

TEMPLATE = app
TARGET = dev
INCLUDEPATH += .

QT += gui
QT += widgets
# Input
SOURCES += hello.cpp
