######################################################################
# Automatically generated by qmake (3.0) Wed Jan 4 13:30:22 2017
######################################################################

TEMPLATE = app
TARGET = dev
INCLUDEPATH += .
HEADERS += Spectre.hpp VisuWidget.hpp
QMAKE_CFLAGS_RELEASE -= -O2
PRE_TARGETDEPS += ./libfft.a


LIBS += -L./ -lfft -lm

QT += gui
QT += widgets
# Input
SOURCES += hello.cpp Spectre.cpp VisuWidget.cpp
